name: 'Publish javadoc'

on:
  push:
    tags: ['*']
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: false
  workflow_call:
    inputs:
      dry_run:
        description: 'Dry run'
        type: boolean
        required: true

defaults:
  run:
    shell: bash

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:

  build-javadoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build javadoc
        uses: ./.github/actions/build
        with:
          tasks: 'dokkaHtml'
          artifact-name: 'javadoc'
          path-to-upload: "build/dokka/html/**/*"

  publish-javadoc:
    needs: [build-javadoc]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.publish.outputs.page_url }}
    steps:
      - name: Download javadoc
        uses: actions/download-artifact@v3
        with:
          path: ./
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'javadoc'
      - name: Deploy to GitHub Pages
        if: ${{ !inputs.dry_run }}
        id: deployment
        uses: actions/deploy-pages@v1

  test-readme-links:
    needs: [publish-javadoc]
    uses: ./.github/workflows/test-readme-links.yml
